// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                     int64              `json:"id"`
	Username               string             `json:"username"`
	Email                  string             `json:"email"`
	PasswordHash           string             `json:"password_hash"`
	RefreshToken           pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiration pgtype.Timestamptz `json:"refresh_token_expiration"`
	IsVerified             bool               `json:"is_verified"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}
