// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserById(ctx context.Context, id int64) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	PatchUserIsVerifiedById(ctx context.Context, arg PatchUserIsVerifiedByIdParams) (User, error)
	PatchUserRefreshTokenById(ctx context.Context, arg PatchUserRefreshTokenByIdParams) (User, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
