// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.user.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.RefreshToken,
			&i.RefreshTokenExpiration,
			&i.IsVerified,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchUserIsVerifiedById = `-- name: PatchUserIsVerifiedById :one
UPDATE users
SET is_verified = $2
WHERE id = $1
RETURNING id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at
`

type PatchUserIsVerifiedByIdParams struct {
	ID         int64 `json:"id"`
	IsVerified bool  `json:"is_verified"`
}

func (q *Queries) PatchUserIsVerifiedById(ctx context.Context, arg PatchUserIsVerifiedByIdParams) (User, error) {
	row := q.db.QueryRow(ctx, patchUserIsVerifiedById, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const patchUserRefreshTokenById = `-- name: PatchUserRefreshTokenById :one
UPDATE users
SET refresh_token = $2,
    refresh_token_expiration = $3
WHERE id = $1
RETURNING id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at
`

type PatchUserRefreshTokenByIdParams struct {
	ID                     int64              `json:"id"`
	RefreshToken           pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiration pgtype.Timestamptz `json:"refresh_token_expiration"`
}

func (q *Queries) PatchUserRefreshTokenById(ctx context.Context, arg PatchUserRefreshTokenByIdParams) (User, error) {
	row := q.db.QueryRow(ctx, patchUserRefreshTokenById, arg.ID, arg.RefreshToken, arg.RefreshTokenExpiration)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :one
UPDATE users
SET username = $2, email = $3, password_hash = $4
WHERE id = $1
RETURNING id, username, email, password_hash, refresh_token, refresh_token_expiration, is_verified, is_active, created_at
`

type UpdateUserByIdParams struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserById,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.RefreshTokenExpiration,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
