auth_plugin /mosquitto/go-auth.so

auth_opt_backends http
auth_opt_config_file /mosquitto/go-auth/go-auth.conf

auth_opt_http_host ende-api
auth_opt_http_port 7021
auth_opt_http_getuser_uri /api/notificationAuth/user
auth_opt_http_superuser_uri /api/notificationAuth/superuser
auth_opt_http_aclcheck_uri /api/notificationAuth/acl
auth_opt_http_params_mode form

# Method mappings (Mosquitto sends data via POST)
auth_opt_http_with_tls false
