# This is a Mosquitto configuration file that creates a listener on port 1883
# that allows unauthenticated access.

listener 1884
allow_anonymous false

listener 8893
protocol websockets
allow_anonymous false

persistence true
persistence_location /mosquitto/data
persistent_client_expiration 10m
max_queued_messages 100
autosave_interval 1000
autosave_on_changes true

# go auth
include_dir /etc/mosquitto/conf.d